### ISSUE TITLE
I do not understand on how to make a post private.

### ISSUE THREAD

**Issue by notalentgeek** [Diyzzuf/grav-plugin-private#18]
What I have done are these.
- These are part of my private.yaml.

``` markdown
enabled: true

routes:
  login: "/login"
  logout: "/logout"

# MUST BE AN ALPHANUMERIC CHAR
# Generator : http://www.sethcardoza.com/tools/random-password-generator/
session_ss: random_value


private_site: false
private_tag: hidden
enable_username: false
```
- I go to system.yaml and add `private_tag` to the taxonomies. Here is my system.yaml.

``` markdown
title: notalentgeek
author:
  name: notalentgeek
  email: mikael.pratama@yahoo.com
taxonomies:
  - category
  - private_tag
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
```
- I go to the default.md of my post that I want to make it private and add this to the front matter `tag: [private_tag]`. Here is my example of default.md.

``` markdown

---
title: 'A Private Blog Post'
published: true
process:
    markdown: true
child_type: default
routable: true
cache_enable: true
visible: true
content:
    items: @self.children
    order:
        by: title
        dir: asc
    pagination: true
tag: [private_tag]

---
```

However my post was still there and there is no password prompt. I think I might miss a thing or more but I never have experience with this .yaml things before.

**Comment by Diyzzuf** [comment]
on your config file, `private_tag` is set to `hidden`.
So, on your page, use `hidden` for tag, not `private_tag`

```
---
title: 'A Private Blog Post'
published: true
process:
    markdown: true
child_type: default
routable: true
cache_enable: true
visible: true
content:
    items: @self.children
    order:
        by: title
        dir: asc
    pagination: true
tag: [hidden]
---
```
